version: '3.1'
services:

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=testpass
    ports:
      - 127.0.0.1:5432:5432
    restart: always

  elastic:
    image: elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
    restart: always
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
